# ==============================================================================
# SCRIPT: Identification of BnA-BnC homoeologous gene pairs by Reciprocal Best Hit
#
# Description:
# This script identifies high-confidence homoeologous gene pairs between the
# BnA and BnC subgenomes of Brassica napus using the Reciprocal Best Hit (RBH)
# approach.
#
# The workflow:
#   1. Reads the bidirectional BLASTp results generated by
#      01_prepare_reference_and_BLAST.sh.
#   2. Filters BLAST hits using a minimum sequence identity of 70%.
#   3. Retains the highest-bitscore hit for each query sequence.
#   4. Identifies reciprocal best-hit pairs between BnA and BnC.
#   5. Exports best hits, RBH pairs and summary statistics as TSV files.
#   6. Exports the same results to an Excel workbook.
#   7. Generates a text file describing the RBH analysis and summary statistics.
#
# Reference genome:
# Brassica napus cv. Darmor-bzh v10
# ==============================================================================


# ==============================================================================
# 0. Required packages
# ==============================================================================

library(tidyverse)
library(openxlsx)


# ==============================================================================
# 1. Define input and output paths
# ==============================================================================

# WORK_DIR must correspond to the same working directory used by
# 01_prepare_reference_and_BLAST.sh.
#
# By default, the script expects the following BLASTp output files:
#   ./Homologous_Analysis_DarmorV10/results/A_vs_C.tsv
#   ./Homologous_Analysis_DarmorV10/results/C_vs_A.tsv
#
# WORK_DIR can also be supplied as an environment variable.

work_dir <- Sys.getenv(
  "WORK_DIR",
  unset = "./Homologous_Analysis_DarmorV10"
)

blast_files <- list(
  A_vs_C = file.path(work_dir, "results", "A_vs_C.tsv"),
  C_vs_A = file.path(work_dir, "results", "C_vs_A.tsv")
)

# Directory for final RBH results.
final_path <- file.path(work_dir, "results", "Final_results")
dir.create(final_path, recursive = TRUE, showWarnings = FALSE)

# Directory for the Excel workbook.
final_path_excel <- file.path(final_path, "Excel")
dir.create(final_path_excel, recursive = TRUE, showWarnings = FALSE)

# Check that both BLASTp input files are available.
for (file in blast_files) {
  if (!file.exists(file)) {
    stop("BLASTp input file not found: ", file)
  }
}


# ==============================================================================
# 2. Function to read BLAST tabular output
# ==============================================================================

read_blast <- function(file) {
  colnames <- c(
    "qseqid", "sseqid", "pident", "length", "mismatch", "gapopen",
    "qstart", "qend", "sstart", "send", "evalue", "bitscore"
  )
  
  read_tsv(
    file,
    col_names = colnames,
    show_col_types = FALSE
  )
}


# ==============================================================================
# 3. Function to identify Reciprocal Best Hits
# ==============================================================================

get_rbh <- function(forward, reverse, min_identity = 70) {
  
  # Filter BLAST hits by minimum percentage sequence identity.
  forward <- forward %>%
    filter(pident >= min_identity)
  
  reverse <- reverse %>%
    filter(pident >= min_identity)
  
  # Retain the highest-bitscore hit for each query sequence in the
  # BnA-to-BnC BLASTp search.
  best_forward <- forward %>%
    group_by(qseqid) %>%
    slice_max(bitscore, n = 1) %>%
    ungroup()
  
  # Retain the highest-bitscore hit for each query sequence in the
  # BnC-to-BnA BLASTp search.
  best_reverse <- reverse %>%
    group_by(qseqid) %>%
    slice_max(bitscore, n = 1) %>%
    ungroup()
  
  # Identify Reciprocal Best Hits.
  # A pair is retained when a BnA protein identifies a BnC protein as its
  # best hit and the same BnC protein identifies that BnA protein as its
  # best hit in the reverse BLASTp search.
  rbh <- best_forward %>%
    inner_join(
      best_reverse,
      by = c("qseqid" = "sseqid", "sseqid" = "qseqid"),
      suffix = c("_fwd", "_rev")
    ) %>%
    transmute(
      gene_A = qseqid,
      gene_C = sseqid,
      pident = pident_fwd,
      bitscore = bitscore_fwd,
      evalue = evalue_fwd,
      RBH = TRUE
    )
  
  # Generate summary statistics for the RBH analysis.
  summary_df <- tibble(
    Metric = c(
      "Genes with hits in A",
      "Genes with hits in C",
      "Best hits A",
      "Best hits C",
      "RBH pairs",
      "Genes lost from A (non-RBH)",
      "Genes lost from C (non-RBH)"
    ),
    Value = c(
      n_distinct(forward$qseqid),
      n_distinct(reverse$qseqid),
      nrow(best_forward),
      nrow(best_reverse),
      nrow(rbh),
      nrow(best_forward) - nrow(rbh),
      nrow(best_reverse) - nrow(rbh)
    )
  )
  
  return(
    list(
      rbh = rbh,
      summary = summary_df,
      best_forward = best_forward,
      best_reverse = best_reverse
    )
  )
}


# ==============================================================================
# 4. Run the RBH analysis
# ==============================================================================

cat("Processing BnA vs BnC Reciprocal Best Hit analysis...\n")

forward <- read_blast(blast_files$A_vs_C)
reverse <- read_blast(blast_files$C_vs_A)

rbh_results <- get_rbh(
  forward = forward,
  reverse = reverse,
  min_identity = 70
)


# ==============================================================================
# 5. Save individual TSV output files
# ==============================================================================

write_tsv(
  rbh_results$best_forward,
  file.path(final_path, "Best_hits_A_vs_C.tsv")
)

write_tsv(
  rbh_results$best_reverse,
  file.path(final_path, "Best_hits_C_vs_A.tsv")
)

write_tsv(
  rbh_results$rbh,
  file.path(final_path, "RBH_pairs.tsv")
)

write_tsv(
  rbh_results$summary,
  file.path(final_path, "RBH_summary.tsv")
)


# ==============================================================================
# 6. Save all RBH results to an Excel workbook
# ==============================================================================

wb <- createWorkbook()

addWorksheet(wb, "Best_A_vs_C")
addWorksheet(wb, "Best_C_vs_A")
addWorksheet(wb, "RBH")
addWorksheet(wb, "Summary")

writeData(
  wb,
  "Best_A_vs_C",
  rbh_results$best_forward
)

writeData(
  wb,
  "Best_C_vs_A",
  rbh_results$best_reverse
)

writeData(
  wb,
  "RBH",
  rbh_results$rbh
)

writeData(
  wb,
  "Summary",
  rbh_results$summary
)

saveWorkbook(
  wb,
  file.path(final_path_excel, "RBH_results.xlsx"),
  overwrite = TRUE
)


# ==============================================================================
# 7. Export RBH pipeline description
# ==============================================================================

pipeline_text <- paste(
  "RBH PIPELINE DESCRIPTION\n",
  "-------------------------\n\n",
  "This analysis identifies high-confidence homoeologous gene pairs\n",
  "between the BnA and BnC subgenomes of Brassica napus using the Reciprocal Best Hit (RBH) approach.\n\n",
  "Step 1: Bidirectional BLASTp searches (BnA vs BnC and BnC vs BnA) were performed.\n",
  "Step 2: Hits were filtered using a minimum sequence identity of >=70%.\n",
  "Step 3: For each query sequence, the top hit based on the highest bitscore was retained.\n",
  "Step 4: Reciprocal Best Hits were defined when a BnA protein identified a BnC protein as its best hit and the same BnC protein identified that BnA protein as its best hit in the reverse search.\n",
  "Step 5: Non-reciprocal hits were discarded to reduce ambiguous or paralogous relationships.\n",
  "Step 6: The final RBH table contains BnA-BnC homoeologous pairs.\n\n",
  "SUMMARY STATISTICS\n",
  paste(
    rbh_results$summary$Metric,
    rbh_results$summary$Value,
    collapse = "; "
  ),
  "\n"
)

writeLines(
  pipeline_text,
  file.path(final_path, "RBH_pipeline_description.txt")
)

