# ==============================================================================
# SCRIPT: RBH homoeolog visualization filtered by expression (TPM)
# Date: 2026
# Description: Generates chromosome-scale synteny plots and an orthology matrix
#              using expressed BnA-BnC Reciprocal Best Hit (RBH) gene pairs.
# ==============================================================================

# 1. Load packages
# ------------------------------------------------------------------------------
suppressPackageStartupMessages({
  library(tidyverse)
  library(circlize)
  library(readxl)
  library(writexl)
  library(RColorBrewer)
})

# 2. Define directories and input files
# ------------------------------------------------------------------------------
# WORK_DIR should correspond to the working directory generated by the previous
# scripts in this workflow.
#
# REFERENCE_DIR should contain the Brassica napus cv. Darmor-bzh v10 annotation
# file downloaded from BnaOmics:
#   BnapusDarmor-bzh_annotation.gff.gz
#
# TPM_PATH should point to the TPM-normalized expression matrix used for the
# expression analysis. The first column must contain gene identifiers.
#
# LINEAGES contains the prefixes used to identify the biological lines or
# genotypes in the TPM matrix. Replace the example names below with the prefixes
# used in your own expression matrix.
#
# IMPORTANT: TPM sample columns must begin with the corresponding lineage prefix
# because the script selects lineage-specific samples using starts_with(lin).
# For example, if a lineage is defined as "Line1", valid sample names include
# "Line1_rep1", "Line1_rep2", etc. Names such as "rep1_Line1" will not be
# selected by the current workflow.

WORK_DIR <- Sys.getenv(
  "WORK_DIR",
  unset = "./Homologous_Analysis_DarmorV10"
)

REFERENCE_DIR <- Sys.getenv(
  "REFERENCE_DIR",
  unset = "./reference"
)

TPM_PATH <- Sys.getenv(
  "TPM_PATH",
  unset = "./input/tpm_counts.xlsx"
)

OUT_DIR <- Sys.getenv(
  "OUT_DIR",
  unset = file.path(WORK_DIR, "results", "Circos_RBH_expression")
)

# Input files
GFF_PATH <- file.path(
  REFERENCE_DIR,
  "BnapusDarmor-bzh_annotation.gff.gz"
)

RBH_PATH <- file.path(
  WORK_DIR,
  "results",
  "Final_results",
  "RBH_pairs.tsv"
)

# Replace these example lineage names with the prefixes used in the TPM matrix.
lineages <- c("Line1", "Line2", "Line3")

# Create output directory
dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)

# Check required input files
if (!file.exists(GFF_PATH)) {
  stop("GFF3 annotation file not found: ", GFF_PATH)
}

if (!file.exists(RBH_PATH)) {
  stop("RBH file not found: ", RBH_PATH)
}

if (!file.exists(TPM_PATH)) {
  stop("TPM expression file not found: ", TPM_PATH)
}

# 3. Read and process static genomic data
# ------------------------------------------------------------------------------

# --- A) Read RBH table ---
message(">>> Reading RBH file...")
rbh_data <- read_tsv(RBH_PATH, show_col_types = FALSE)

# --- B) Read GFF3 annotation ---
message(">>> Reading GFF3 annotation and filtering mRNA features...")
gff_data <- read_tsv(
  GFF_PATH,
  comment = "#",
  col_names = c(
    "seqid",
    "source",
    "type",
    "start",
    "end",
    "score",
    "strand",
    "phase",
    "attributes"
  ),
  show_col_types = FALSE
)

# Retain only mRNA features and extract the sequence identifier from the ID field.
genes_gff <- gff_data %>%
  filter(type == "mRNA") %>%
  mutate(gene_id_clean = str_extract(attributes, "(?<=ID=)[^;]+")) %>%
  select(seqid, start, end, gene_id_clean)

# --- C) Map genomic coordinates to RBH pairs ---
message(">>> Mapping genomic coordinates to RBH pairs...")
rbh_coords_master <- rbh_data %>%
  inner_join(genes_gff, by = c("gene_A" = "gene_id_clean")) %>%
  rename(seq_A = seqid, start_A = start, end_A = end) %>%
  inner_join(genes_gff, by = c("gene_C" = "gene_id_clean")) %>%
  rename(seq_C = seqid, start_C = start, end_C = end)

message("Total RBH pairs in the genomic master list: ", nrow(rbh_coords_master))

# 4. Read TPM expression data
# ------------------------------------------------------------------------------
message(">>> Reading TPM expression matrix...")

# The first column is assumed to contain gene identifiers.
tpm_data <- read_xlsx(TPM_PATH)
colnames(tpm_data)[1] <- "GeneID"

# ============================================================================== 
# 5. Loop through lineages
# Generates three figures for each lineage:
#   1. Circular synteny plot with buffered links
#   2. Circular synteny plot with thin links
#   3. Orthology matrix showing the number of expressed RBH pairs per
#      chromosome combination
# ============================================================================== 

# Global visual settings
visual_buffer <- 5000
transp_thick <- 0.15
transp_thin <- 0.60

# Prepare chromosome limits and colors.
main_chrs_A <- paste0("A", sprintf("%02d", 1:10))
main_chrs_C <- paste0("C", sprintf("%02d", 1:9))
all_main_chrs <- c(main_chrs_A, main_chrs_C)

palette_A <- colorRampPalette(brewer.pal(10, "Paired"))(10)
names(palette_A) <- main_chrs_A
palette_C <- setNames(rep("grey70", 9), main_chrs_C)
grid_colors <- c(palette_A, palette_C)

# Calculate chromosome sizes for plotting.
chr_ranges <- genes_gff %>%
  filter(seqid %in% all_main_chrs) %>%
  group_by(seqid) %>%
  summarise(min = 0, max = max(end)) %>%
  slice(match(all_main_chrs, seqid))

# --- Start lineage loop ---
for (lin in lineages) {
  
  message("\n--------------------------------------------------")
  message("Processing lineage: ", lin)
  
  lin_dir <- file.path(OUT_DIR, lin)
  dir.create(lin_dir, showWarnings = FALSE, recursive = TRUE)
  
  # 5.1 Filter expressed genes
  genes_expressed <- tpm_data %>%
    select(GeneID, starts_with(lin)) %>%
    mutate(Total_TPM = rowSums(across(where(is.numeric)))) %>%
    filter(Total_TPM >= 1) %>%
    pull(GeneID)
  
  # 5.2 Filter RBH pairs
  rbh_filtered <- rbh_coords_master %>%
    filter(gene_A %in% genes_expressed & gene_C %in% genes_expressed) %>%
    filter(seq_A %in% main_chrs_A & seq_C %in% main_chrs_C)
  
  message("  Expressed RBH pairs: ", nrow(rbh_filtered))
  
  if (nrow(rbh_filtered) == 0) {
    message("  [WARNING] No expressed RBH pairs found. Skipping this lineage.")
    next
  }
  
  # Save filtered RBH table.
  write_xlsx(
    list(Expressed_Homoeologs = rbh_filtered),
    file.path(lin_dir, paste0("Expressed_RBH_Pairs_", lin, ".xlsx"))
  )
  
  # ============================================================================
  # FIGURE 1: Circular synteny plot with buffered links
  # ============================================================================
  
  # Prepare plotting coordinates while keeping buffered regions inside the
  # chromosome boundaries.
  plot_data_thick <- rbh_filtered %>%
    inner_join(
      chr_ranges %>% select(seqid, max_A = max),
      by = c("seq_A" = "seqid")
    ) %>%
    inner_join(
      chr_ranges %>% select(seqid, max_C = max),
      by = c("seq_C" = "seqid")
    ) %>%
    mutate(
      start_A_plot = pmax(0, start_A - visual_buffer),
      end_A_plot = pmin(max_A, end_A + visual_buffer),
      start_C_plot = pmax(0, start_C - visual_buffer),
      end_C_plot = pmin(max_C, end_C + visual_buffer)
    )
  
  png(
    file.path(lin_dir, paste0("Synteny_Circular_", lin, ".png")),
    width = 3000,
    height = 3000,
    res = 300
  )
  
  circos.clear()
  
  # Expanded canvas limits ensure that plot titles are not clipped.
  circos.par(
    gap.after = c(rep(2, 9), 15, rep(2, 8), 15),
    canvas.ylim = c(-1.3, 1.3),
    points.overflow.warning = FALSE
  )
  
  # Initialize chromosome sectors.
  circos.genomicInitialize(
    data.frame(
      chr = chr_ranges$seqid,
      start = chr_ranges$min,
      end = chr_ranges$max
    ),
    major.by = 10000000,
    axis.labels.cex = 0.3,
    labels.cex = 1.3
  )
  
  # Chromosome track.
  circos.track(
    ylim = c(0, 1),
    panel.fun = function(x, y) {
      chr_name <- CELL_META$sector.index
      circos.rect(
        CELL_META$xlim[1],
        0,
        CELL_META$xlim[2],
        1,
        col = grid_colors[chr_name],
        border = NA
      )
    },
    track.height = 0.05,
    bg.border = NA
  )
  
  # Link colors are assigned according to the BnA chromosome.
  link_colors <- palette_A[plot_data_thick$seq_A]
  link_colors_alpha <- sapply(
    link_colors,
    function(x) adjustcolor(x, alpha.f = transp_thick)
  )
  
  # Draw buffered links.
  circos.genomicLink(
    region1 = plot_data_thick %>%
      select(chr = seq_A, start = start_A_plot, end = end_A_plot),
    region2 = plot_data_thick %>%
      select(chr = seq_C, start = start_C_plot, end = end_C_plot),
    col = link_colors_alpha,
    border = link_colors_alpha,
    lwd = 0.1
  )
  
  text(
    0,
    1.15,
    paste0("Synteny: ", lin),
    cex = 2,
    font = 2,
    adj = c(0.5, 0)
  )
  
  text(
    0,
    1.10,
    paste0("Pairs: ", nrow(rbh_filtered)),
    cex = 1.4,
    font = 3
  )
  
  dev.off()
  circos.clear()
  
  message("  -> Circular synteny plot with buffered links saved.")
  
  # ============================================================================
  # FIGURE 2: Circular synteny plot with thin links
  # ============================================================================
  
  png(
    file.path(lin_dir, paste0("Synteny_Circular_Tiny_", lin, ".png")),
    width = 3000,
    height = 3000,
    res = 300
  )
  
  circos.clear()
  
  # Use the same chromosome layout as Figure 1.
  circos.par(
    gap.after = c(rep(2, 9), 15, rep(2, 8), 15),
    canvas.ylim = c(-1.3, 1.3),
    points.overflow.warning = FALSE
  )
  
  # Initialize chromosome sectors.
  circos.genomicInitialize(
    data.frame(
      chr = chr_ranges$seqid,
      start = chr_ranges$min,
      end = chr_ranges$max
    ),
    major.by = 10000000,
    axis.labels.cex = 0.3,
    labels.cex = 1.3
  )
  
  # Chromosome track.
  circos.track(
    ylim = c(0, 1),
    panel.fun = function(x, y) {
      chr_name <- CELL_META$sector.index
      circos.rect(
        CELL_META$xlim[1],
        0,
        CELL_META$xlim[2],
        1,
        col = grid_colors[chr_name],
        border = NA
      )
    },
    track.height = 0.05,
    bg.border = NA
  )
  
  # Link colors are assigned according to the BnA chromosome.
  link_colors <- palette_A[rbh_filtered$seq_A]
  link_colors_alpha <- sapply(
    link_colors,
    function(x) adjustcolor(x, alpha.f = transp_thin)
  )
  
  # Draw thin links using the original gene coordinates.
  circos.genomicLink(
    region1 = rbh_filtered %>%
      select(chr = seq_A, start = start_A, end = end_A),
    region2 = rbh_filtered %>%
      select(chr = seq_C, start = start_C, end = end_C),
    col = link_colors_alpha,
    border = NA,
    lwd = 0.5
  )
  
  text(
    0,
    1.15,
    paste0("Synteny: ", lin),
    cex = 2,
    font = 2,
    adj = c(0.5, 0)
  )
  
  text(
    0,
    1.10,
    paste0("Pairs: ", nrow(rbh_filtered)),
    cex = 1.4,
    font = 3
  )
  
  dev.off()
  circos.clear()
  
  message("  -> Circular synteny plot with thin links saved.")
  
  # ============================================================================
  # FIGURE 3: Orthology matrix
  # ============================================================================
  
  heatmap_data <- rbh_filtered %>%
    count(seq_A, seq_C) %>%
    mutate(
      seq_A = factor(seq_A, levels = rev(main_chrs_A)),
      seq_C = factor(seq_C, levels = main_chrs_C)
    )
  
  p_heatmap <- ggplot(
    heatmap_data,
    aes(x = seq_C, y = seq_A, fill = n)
  ) +
    geom_tile(color = "white") +
    geom_text(aes(label = n), color = "black", size = 4) +
    scale_fill_gradient(
      low = "#B2DFEE",
      high = "#68228B",
      name = "Nº Genes"
    ) +
    theme_minimal() +
    labs(
      title = paste0("Orthology Matrix: ", lin),
      subtitle = paste0(
        "Expressed RBH gene pairs (Total: ",
        nrow(rbh_filtered),
        ")"
      ),
      x = "Subgenome C",
      y = "Subgenome A"
    ) +
    theme(
      axis.text = element_text(size = 11, face = "bold"),
      panel.grid = element_blank()
    )
  
  ggsave(
    file.path(lin_dir, paste0("Heatmap_Counts_", lin, ".png")),
    p_heatmap,
    width = 10,
    height = 8,
    dpi = 300
  )
  
  message("  -> Orthology matrix saved.")
}
