# ==============================================================================
# SCRIPT: Homoeolog Expression Bias (HEB) analysis
#
# Description:
# This script calculates homoeolog expression bias between BnA and BnC
# homoeologous gene pairs in Brassica napus using TPM-normalized expression
# values.
#
# For each lineage/genotype, the workflow:
#   1. Selects Unprimed and Primed samples from the TPM matrix.
#   2. Matches BnA and BnC genes using the Reciprocal Best Hit (RBH) table.
#   3. Retains homoeologous pairs with detectable expression (TPM >= 1 in at
#      least one condition).
#   4. Calculates mean TPM values for BnA and BnC homoeologs.
#   5. Calculates log2 fold change as log2((Mean_A + 1) / (Mean_C + 1)).
#   6. Tests BnA versus BnC expression using a paired Student's t-test on
#      log2-transformed TPM values across corresponding biological replicates.
#   7. Applies Benjamini-Hochberg correction for multiple testing.
#   8. Classifies each homoeologous pair as "A bias", "C bias", or "No bias".
#   9. Records whether the bias classification is stable or changes between
#      Unprimed and Primed conditions.
#
# IMPORTANT:
# TPM sample columns must begin with the corresponding lineage prefix because
# lineage-specific samples are selected using the beginning of the column name.
#
# Sample names must also contain the condition patterns defined below:
#   "_U" for Unprimed samples
#   "_P" for Primed samples
#
# For example, if a lineage is defined as "Line1", valid sample names include:
#   Line1_U_rep1
#   Line1_U_rep2
#   Line1_P_rep1
#   Line1_P_rep2
#
# The Unprimed and Primed groups must contain corresponding biological
# replicates in the same order so that the paired t-test is valid.
# ==============================================================================


# ==============================================================================
# 1. Load required packages
# ==============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(readxl)
  library(writexl)
})


# ==============================================================================
# 2. Define input and output paths
# ==============================================================================

# RBH_FILE:
# Reciprocal Best Hit table generated by 02_identify_RBH.R.
#
# TPM_FILE:
# TPM-normalized expression matrix in Excel format.
#
# OUTPUT_DIR:
# Directory where the HEB analysis tables will be saved.
#
# These paths can be modified here or supplied as environment variables when
# running the script.

RBH_FILE <- Sys.getenv(
  "RBH_FILE",
  unset = "./Homologous_Analysis_DarmorV10/results/Final_results/RBH_pairs.tsv"
)

TPM_FILE <- Sys.getenv(
  "TPM_FILE",
  unset = "./data/tpm_counts.xlsx"
)

OUTPUT_DIR <- Sys.getenv(
  "OUTPUT_DIR",
  unset = "./results/Homeolog_expression_bias"
)


# Check that required input files exist.
if (!file.exists(RBH_FILE)) {
  stop(
    paste0(
      "RBH file not found: ",
      RBH_FILE,
      "\nSet RBH_FILE to the correct path before running the script."
    )
  )
}

if (!file.exists(TPM_FILE)) {
  stop(
    paste0(
      "TPM file not found: ",
      TPM_FILE,
      "\nSet TPM_FILE to the correct path before running the script."
    )
  )
}


# Create output directory.
dir.create(
  OUTPUT_DIR,
  showWarnings = FALSE,
  recursive = TRUE
)


# ==============================================================================
# 3. Define analysis parameters
# ==============================================================================

# Replace these example lineage names with the prefixes used in the TPM matrix.
lineages <- c("Line1", "Line2", "Line3")

# Sample-name patterns used to identify experimental conditions.
pattern_UP <- "_U"
pattern_P  <- "_P"

# Statistical thresholds used to classify homoeolog expression bias.
bias_lfc_cutoff <- 1
p_adj_cutoff    <- 0.05


# ==============================================================================
# 4. Load RBH and TPM data
# ==============================================================================

message(">>> Loading RBH and TPM data...")

rbh_data <- read_tsv(
  RBH_FILE,
  show_col_types = FALSE
) %>%
  select(gene_A, gene_C) %>%
  distinct()


tpm_data <- read_xlsx(TPM_FILE)

# The first column is assumed to contain gene identifiers.
colnames(tpm_data)[1] <- "GeneID"


# ==============================================================================
# 5. Paired t-test function
# ==============================================================================

# Expression values from BnA and BnC are compared across corresponding
# biological replicates using a paired Student's t-test after log2(TPM + 1)
# transformation.

calc_pval <- function(vals_A, vals_C) {
  
  # Preserve replicate pairing when removing missing values.
  valid_pairs <- complete.cases(vals_A, vals_C)
  vals_A <- vals_A[valid_pairs]
  vals_C <- vals_C[valid_pairs]
  
  if (length(vals_A) < 2 || length(vals_C) < 2) {
    return(1)
  }
  
  if (sd(vals_A) == 0 && sd(vals_C) == 0) {
    return(1)
  }
  
  tryCatch(
    {
      t.test(
        log2(vals_A + 1),
        log2(vals_C + 1),
        paired = TRUE
      )$p.value
    },
    error = function(e) 1
  )
}


# ==============================================================================
# 6. Calculate homoeolog expression bias for each lineage
# ==============================================================================

for (lin in lineages) {
  
  message(paste0("\n--------------------------------------------------"))
  message(paste0("Processing lineage: ", lin))
  
  # ---------------------------------------------------------------------------
  # 6.1. Identify lineage-specific Unprimed and Primed sample columns
  # ---------------------------------------------------------------------------
  
  all_cols <- colnames(tpm_data)
  
  lin_cols <- grep(
    paste0("^", lin),
    all_cols,
    value = TRUE
  )
  
  cols_UP <- grep(
    pattern_UP,
    lin_cols,
    value = TRUE
  )
  
  cols_P <- grep(
    pattern_P,
    lin_cols,
    value = TRUE
  )
  
  
  # At least two biological replicates per condition are required for the
  # paired t-test.
  if (length(cols_UP) < 2 || length(cols_P) < 2) {
    message(
      "  [SKIP] Fewer than two Unprimed or Primed sample columns were found."
    )
    next
  }
  
  
  # ---------------------------------------------------------------------------
  # 6.2. Prepare lineage-specific TPM data
  # ---------------------------------------------------------------------------
  
  df_lin <- tpm_data %>%
    select(
      GeneID,
      all_of(cols_UP),
      all_of(cols_P)
    )
  
  
  # Match expression values to the BnA and BnC genes in each RBH pair.
  df_test <- rbh_data %>%
    inner_join(
      df_lin,
      by = c("gene_A" = "GeneID")
    ) %>%
    rename_with(
      ~paste0("A_", .),
      -c(gene_A, gene_C)
    ) %>%
    inner_join(
      df_lin,
      by = c("gene_C" = "GeneID")
    ) %>%
    rename_with(
      ~paste0("C_", .),
      -c(gene_A, gene_C, starts_with("A_"))
    )
  
  
  # ---------------------------------------------------------------------------
  # 6.3. Calculate mean expression and retain expressed homoeolog pairs
  # ---------------------------------------------------------------------------
  
  results <- df_test %>%
    rowwise() %>%
    mutate(
      Mean_A_UP = mean(
        c_across(paste0("A_", cols_UP)),
        na.rm = TRUE
      ),
      Mean_C_UP = mean(
        c_across(paste0("C_", cols_UP)),
        na.rm = TRUE
      ),
      Mean_A_P = mean(
        c_across(paste0("A_", cols_P)),
        na.rm = TRUE
      ),
      Mean_C_P = mean(
        c_across(paste0("C_", cols_P)),
        na.rm = TRUE
      ),
      Expressed =
        (Mean_A_UP >= 1 | Mean_C_UP >= 1) |
        (Mean_A_P >= 1 | Mean_C_P >= 1)
    ) %>%
    ungroup() %>%
    filter(Expressed)
  
  
  # ---------------------------------------------------------------------------
  # 6.4. Calculate log2 fold change and paired t-test p-values
  # ---------------------------------------------------------------------------
  
  results <- results %>%
    rowwise() %>%
    mutate(
      LFC_UP = log2(
        (Mean_A_UP + 1) / (Mean_C_UP + 1)
      ),
      LFC_P = log2(
        (Mean_A_P + 1) / (Mean_C_P + 1)
      ),
      Pval_UP = calc_pval(
        c_across(paste0("A_", cols_UP)),
        c_across(paste0("C_", cols_UP))
      ),
      Pval_P = calc_pval(
        c_across(paste0("A_", cols_P)),
        c_across(paste0("C_", cols_P))
      )
    ) %>%
    ungroup()
  
  
  # ---------------------------------------------------------------------------
  # 6.5. Apply BH correction and classify subgenome expression bias
  # ---------------------------------------------------------------------------
  
  results <- results %>%
    mutate(
      Padj_UP = p.adjust(
        Pval_UP,
        method = "BH"
      ),
      Padj_P = p.adjust(
        Pval_P,
        method = "BH"
      ),
      Bias_UP = case_when(
        LFC_UP > bias_lfc_cutoff &
          Padj_UP < p_adj_cutoff ~ "A bias",
        LFC_UP < -bias_lfc_cutoff &
          Padj_UP < p_adj_cutoff ~ "C bias",
        TRUE ~ "No bias"
      ),
      Bias_P = case_when(
        LFC_P > bias_lfc_cutoff &
          Padj_P < p_adj_cutoff ~ "A bias",
        LFC_P < -bias_lfc_cutoff &
          Padj_P < p_adj_cutoff ~ "C bias",
        TRUE ~ "No bias"
      ),
      Flow = ifelse(
        Bias_UP == Bias_P,
        "Stable",
        "Changed"
      ),
      Transition_Type = paste(
        Bias_UP,
        "->",
        Bias_P
      )
    )
  
  
  # ---------------------------------------------------------------------------
  # 6.6. Reorganize and export results
  # ---------------------------------------------------------------------------
  
  results_export <- results %>%
    select(
      gene_A,
      gene_C,
      Flow,
      Transition_Type,
      Bias_UP,
      Bias_P,
      everything()
    )
  
  
  output_file <- file.path(
    OUTPUT_DIR,
    paste0("Bias_Analysis_", lin, ".xlsx")
  )
  
  
  write_xlsx(
    list(
      Stats_and_Transitions = results_export
    ),
    output_file
  )
  
  
  message(
    "  -> Homoeolog expression bias analysis saved: ",
    output_file
  )
}
