# ==============================================================================
# SCRIPT: Homoeolog expression bias distribution and global transcriptomic dosage
#
# Description:
# This script generates:
#   1. Histograms showing the distribution of homoeolog expression bias for
#      Unprimed and Primed conditions.
#   2. Dot plots showing the global transcriptomic dosage of the BnA and BnC
#      subgenomes in each biological replicate.
#   3. A summary table containing the number and percentage of homoeologous
#      gene pairs classified as A bias, C bias, or No bias.
#
# Inputs:
#   - Bias_Analysis_<Lineage>.xlsx files generated by
#     05_homeolog_expression_bias.R.
#   - The original TPM-normalized expression matrix.
#
# IMPORTANT:
# The histograms use the LFC_UP and LFC_P values calculated by
# 05_homeolog_expression_bias.R. They are not recalculated here, ensuring that
# the plotted values are identical to those used for bias classification.
#
# Global transcriptomic dosage is calculated from the complete TPM matrix,
# independently of the RBH-filtered gene-pair dataset. For each biological
# sample, total TPM is summed separately for genes belonging to the BnA and BnC
# subgenomes, and each subgenome is expressed as a proportion of the combined
# BnA + BnC expression.
#
# TPM sample columns must begin with the corresponding lineage prefix.
# Sample names must also contain the condition patterns defined below:
#   "_U" for Unprimed samples
#   "_P" for Primed samples
# ==============================================================================


# ==============================================================================
# 1. Load required packages
# ==============================================================================

suppressPackageStartupMessages({
  library(readxl)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(scales)
  library(writexl)
})


# ==============================================================================
# 2. Define input and output paths
# ==============================================================================

# BIAS_DIR:
# Directory containing Bias_Analysis_<Lineage>.xlsx files generated by
# 05_homeolog_expression_bias.R.
#
# TPM_FILE:
# Original TPM-normalized expression matrix.
#
# OUTPUT_DIR:
# Directory where figures and summary tables will be saved.

BIAS_DIR <- Sys.getenv(
  "BIAS_DIR",
  unset = "./results/Homeolog_expression_bias"
)

TPM_FILE <- Sys.getenv(
  "TPM_FILE",
  unset = "./data/tpm_counts.xlsx"
)

OUTPUT_DIR <- Sys.getenv(
  "OUTPUT_DIR",
  unset = "./results/Bias_distribution_and_dosage"
)


if (!dir.exists(BIAS_DIR)) {
  stop(
    paste0(
      "Bias-analysis directory not found: ",
      BIAS_DIR,
      "\nRun 05_homeolog_expression_bias.R first or set BIAS_DIR correctly."
    )
  )
}

if (!file.exists(TPM_FILE)) {
  stop(
    paste0(
      "TPM file not found: ",
      TPM_FILE,
      "\nSet TPM_FILE to the correct path before running the script."
    )
  )
}


dir.create(
  OUTPUT_DIR,
  showWarnings = FALSE,
  recursive = TRUE
)


# ==============================================================================
# 3. Define analysis parameters
# ==============================================================================

# Replace these example lineage names with the prefixes used in the TPM matrix
# and in the output files generated by 05_homeolog_expression_bias.R.
lineages <- c("Line1", "Line2", "Line3")

# Sample-name patterns used to identify experimental conditions.
pattern_UP <- "_U"
pattern_P  <- "_P"

# Histogram display range and bin width.
histogram_min <- -10
histogram_max <- 10
histogram_binwidth <- 0.25


# ==============================================================================
# 4. Define plot colors
# ==============================================================================

bias_colors <- c(
  "No bias" = "grey85",
  "C bias"  = "#9BCD9B",
  "A bias"  = "#00BFFF"
)

subgenome_colors <- c(
  "A Subgenome" = "#00BFFF",
  "C Subgenome" = "#9BCD9B"
)


# ==============================================================================
# 5. Load the complete TPM matrix
# ==============================================================================

message(">>> Reading TPM matrix...")

tpm_data <- read_xlsx(TPM_FILE)

# The first column is assumed to contain gene identifiers.
colnames(tpm_data)[1] <- "GeneID"


# ==============================================================================
# 6. Function: bias-distribution histogram
# ==============================================================================

generate_bias_histogram <- function(df, lineage_name, out_path) {
  
  # Use the LFC values calculated in 05_homeolog_expression_bias.R.
  df_long <- bind_rows(
    df %>%
      select(LFC_UP, Bias_UP) %>%
      transmute(
        Condition = "Unprimed",
        Log2_Ratio = LFC_UP,
        Bias_Class = Bias_UP
      ),
    
    df %>%
      select(LFC_P, Bias_P) %>%
      transmute(
        Condition = "Primed",
        Log2_Ratio = LFC_P,
        Bias_Class = Bias_P
      )
  )
  
  df_long$Condition <- factor(
    df_long$Condition,
    levels = c("Unprimed", "Primed")
  )
  
  df_long$Bias_Class <- factor(
    df_long$Bias_Class,
    levels = c("No bias", "C bias", "A bias")
  )
  
  
  # ---------------------------------------------------------------------------
  # 6.1. Calculate annotation height within the visible histogram range
  # ---------------------------------------------------------------------------
  
  values_for_calc <- df_long$Log2_Ratio[
    df_long$Log2_Ratio >= histogram_min &
      df_long$Log2_Ratio <= histogram_max
  ]
  
  if (length(values_for_calc) > 0) {
    h <- hist(
      values_for_calc,
      breaks = seq(
        histogram_min,
        histogram_max,
        by = histogram_binwidth
      ),
      plot = FALSE
    )
    
    max_freq <- max(h$counts)
  } else {
    max_freq <- 1
  }
  
  text_y_pos <- max_freq * 1.05
  graph_y_limit <- max_freq * 1.2
  
  
  # ---------------------------------------------------------------------------
  # 6.2. Compare the number of A-biased and C-biased pairs
  # ---------------------------------------------------------------------------
  
  stats_anno <- df_long %>%
    filter(
      Bias_Class %in% c("A bias", "C bias")
    ) %>%
    group_by(Condition) %>%
    summarise(
      n_A = sum(Bias_Class == "A bias"),
      n_C = sum(Bias_Class == "C bias"),
      .groups = "drop"
    ) %>%
    rowwise() %>%
    mutate(
      p_val = tryCatch(
        chisq.test(c(n_A, n_C))$p.value,
        error = function(e) NA_real_
      ),
      label = case_when(
        is.na(p_val) ~ "P = NA",
        p_val < 2.2e-16 ~ "P < 2.2e-16",
        TRUE ~ paste0(
          "P = ",
          format(
            p_val,
            scientific = TRUE,
            digits = 2
          )
        )
      ),
      direction = case_when(
        n_A > n_C ~ "A > C",
        n_C > n_A ~ "A < C",
        TRUE ~ "A = C"
      ),
      full_label = paste0(
        direction,
        "\n",
        label
      ),
      y_pos = text_y_pos,
      x_pos = histogram_min + 1
    ) %>%
    ungroup()
  
  
  # ---------------------------------------------------------------------------
  # 6.3. Generate histogram
  # ---------------------------------------------------------------------------
  
  p <- ggplot(
    df_long,
    aes(
      x = Log2_Ratio,
      fill = Bias_Class
    )
  ) +
    geom_histogram(
      binwidth = histogram_binwidth,
      position = "stack",
      color = "grey30",
      linewidth = 0.05,
      alpha = 0.6
    ) +
    facet_grid(
      . ~ Condition
    ) +
    geom_text(
      data = stats_anno,
      aes(
        x = x_pos,
        y = y_pos,
        label = full_label
      ),
      inherit.aes = FALSE,
      hjust = 0,
      vjust = 0,
      size = 3.5,
      fontface = "italic"
    ) +
    geom_vline(
      xintercept = 0,
      linetype = "dashed",
      color = "black",
      alpha = 0.6
    ) +
    scale_fill_manual(
      values = bias_colors,
      name = "Bias Category"
    ) +
    coord_cartesian(
      xlim = c(
        histogram_min,
        histogram_max
      ),
      ylim = c(
        0,
        graph_y_limit
      )
    ) +
    labs(
      title = paste0(
        lineage_name,
        ": Subgenome Expression Bias Distribution"
      ),
      y = "Number of Gene Pairs",
      x = expression(
        log[2] ~ (Expression[A] / Expression[C])
      )
    ) +
    theme_classic(
      base_size = 14
    ) +
    theme(
      strip.background = element_rect(
        fill = "#f0f0f0",
        color = NA
      ),
      strip.text = element_text(
        face = "bold",
        size = 12
      ),
      legend.position = "top",
      panel.grid.major.y = element_line(
        color = "grey95"
      ),
      plot.title = element_text(
        face = "bold",
        hjust = 0.5
      )
    )
  
  
  output_file <- file.path(
    out_path,
    paste0(
      "Bias_Distribution_",
      lineage_name,
      ".png"
    )
  )
  
  
  ggsave(
    output_file,
    plot = p,
    width = 10,
    height = 6,
    dpi = 300
  )
  
  
  message(
    "  -> Bias-distribution histogram saved: ",
    output_file
  )
}


# ==============================================================================
# 7. Function: global transcriptomic dosage
# ==============================================================================

generate_global_dosage_dotplot <- function(
    tpm,
    lineage_name,
    out_path
) {
  
  all_cols <- colnames(tpm)
  
  lineage_samples <- grep(
    paste0("^", lineage_name),
    all_cols,
    value = TRUE
  )
  
  
  if (length(lineage_samples) == 0) {
    warning(
      paste0(
        "No TPM sample columns found for lineage '",
        lineage_name,
        "'."
      )
    )
    return(NULL)
  }
  
  
  # Separate genes belonging to each subgenome.
  tpm_A <- tpm %>%
    filter(
      grepl("^A", GeneID)
    )
  
  tpm_C <- tpm %>%
    filter(
      grepl("^C", GeneID)
    )
  
  
  dosage_list <- list()
  
  
  for (sample_name in lineage_samples) {
    
    total_A <- sum(
      tpm_A[[sample_name]],
      na.rm = TRUE
    )
    
    total_C <- sum(
      tpm_C[[sample_name]],
      na.rm = TRUE
    )
    
    total_expression <- total_A + total_C
    
    
    if (total_expression == 0) {
      next
    }
    
    
    condition <- case_when(
      grepl(pattern_UP, sample_name) ~ "Unprimed",
      grepl(pattern_P, sample_name) ~ "Primed",
      TRUE ~ "Unknown"
    )
    
    
    dosage_list[[length(dosage_list) + 1]] <- data.frame(
      Sample = sample_name,
      Condition = condition,
      Subgenome = "A Subgenome",
      Proportion = total_A / total_expression
    )
    
    dosage_list[[length(dosage_list) + 1]] <- data.frame(
      Sample = sample_name,
      Condition = condition,
      Subgenome = "C Subgenome",
      Proportion = total_C / total_expression
    )
  }
  
  
  if (length(dosage_list) == 0) {
    warning(
      paste0(
        "No valid samples were available for lineage '",
        lineage_name,
        "'."
      )
    )
    return(NULL)
  }
  
  
  plot_data <- bind_rows(
    dosage_list
  ) %>%
    filter(
      Condition %in% c(
        "Unprimed",
        "Primed"
      )
    )
  
  
  plot_data$Condition <- factor(
    plot_data$Condition,
    levels = c(
      "Unprimed",
      "Primed"
    )
  )
  
  
  p <- ggplot(
    plot_data,
    aes(
      x = Condition,
      y = Proportion,
      color = Subgenome
    )
  ) +
    geom_point(
      size = 5,
      alpha = 0.7,
      position = position_dodge(
        width = 0.3
      )
    ) +
    scale_color_manual(
      values = subgenome_colors
    ) +
    scale_y_continuous(
      labels = percent_format(
        accuracy = 1
      ),
      limits = c(
        0.48,
        0.52
      )
    ) +
    geom_hline(
      yintercept = 0.5,
      linetype = "dashed",
      color = "grey50"
    ) +
    labs(
      title = paste0(
        lineage_name,
        ": Global Transcriptomic Dosage"
      ),
      subtitle = "Proportion of total TPM assigned to each subgenome",
      y = "Proportion of Total Expression (TPM)",
      x = NULL
    ) +
    theme_classic(
      base_size = 14
    ) +
    theme(
      plot.title = element_text(
        face = "bold",
        hjust = 0.5
      ),
      plot.subtitle = element_text(
        hjust = 0.5,
        color = "grey40"
      ),
      panel.grid.major.y = element_line(
        color = "grey90",
        linetype = "dashed"
      ),
      legend.position = "right",
      axis.text.x = element_text(
        size = 12,
        face = "bold"
      )
    )
  
  
  output_file <- file.path(
    out_path,
    paste0(
      "Global_Transcriptomic_Dosage_",
      lineage_name,
      ".png"
    )
  )
  
  
  ggsave(
    output_file,
    plot = p,
    width = 6,
    height = 5,
    dpi = 300
  )
  
  
  write_xlsx(
    list(
      Global_Dosage = plot_data
    ),
    file.path(
      out_path,
      paste0(
        "Global_Transcriptomic_Dosage_",
        lineage_name,
        ".xlsx"
      )
    )
  )
  
  
  message(
    "  -> Global transcriptomic dosage plot saved: ",
    output_file
  )
  
  
  return(
    plot_data
  )
}


# ==============================================================================
# 8. Generate figures and bias summaries for each lineage
# ==============================================================================

message(
  ">>> Generating bias-distribution histograms and global dosage plots..."
)


summary_list <- list()


for (lin in lineages) {
  
  message(
    paste0(
      "\n--------------------------------------------------"
    )
  )
  
  message(
    paste0(
      "Processing lineage: ",
      lin
    )
  )
  
  
  bias_file <- file.path(
    BIAS_DIR,
    paste0(
      "Bias_Analysis_",
      lin,
      ".xlsx"
    )
  )
  
  
  if (!file.exists(bias_file)) {
    warning(
      paste0(
        "Bias-analysis file not found for lineage '",
        lin,
        "': ",
        bias_file
      )
    )
    next
  }
  
  
  df_bias <- read_excel(
    bias_file
  )
  
  
  df_clean <- df_bias %>%
    filter(
      !is.na(LFC_UP),
      !is.na(LFC_P),
      Bias_UP %in% c(
        "A bias",
        "C bias",
        "No bias"
      ),
      Bias_P %in% c(
        "A bias",
        "C bias",
        "No bias"
      )
    )
  
  
  # ---------------------------------------------------------------------------
  # 8.1. Bias-distribution histogram
  # ---------------------------------------------------------------------------
  
  generate_bias_histogram(
    df_clean,
    lin,
    OUTPUT_DIR
  )
  
  
  # ---------------------------------------------------------------------------
  # 8.2. Global transcriptomic dosage
  # ---------------------------------------------------------------------------
  
  generate_global_dosage_dotplot(
    tpm_data,
    lin,
    OUTPUT_DIR
  )
  
  
  # ---------------------------------------------------------------------------
  # 8.3. Bias-category summary
  # ---------------------------------------------------------------------------
  
  total_pairs <- nrow(
    df_clean
  )
  
  
  up_counts <- df_clean %>%
    count(
      Bias_UP,
      name = "n"
    ) %>%
    mutate(
      Condition = "Unprimed",
      Lineage = lin,
      Total = total_pairs,
      Percent = round(
        (n / total_pairs) * 100,
        2
      )
    ) %>%
    rename(
      Bias_Class = Bias_UP
    )
  
  
  p_counts <- df_clean %>%
    count(
      Bias_P,
      name = "n"
    ) %>%
    mutate(
      Condition = "Primed",
      Lineage = lin,
      Total = total_pairs,
      Percent = round(
        (n / total_pairs) * 100,
        2
      )
    ) %>%
    rename(
      Bias_Class = Bias_P
    )
  
  
  summary_list[[lin]] <- bind_rows(
    up_counts,
    p_counts
  )
}


# ==============================================================================
# 9. Export bias summary
# ==============================================================================

if (length(summary_list) > 0) {
  
  summary_df <- bind_rows(
    summary_list
  ) %>%
    select(
      Lineage,
      Condition,
      Bias_Class,
      n,
      Total,
      Percent
    )
  
  
  summary_file <- file.path(
    OUTPUT_DIR,
    "Summary_Bias_All_Lineages.xlsx"
  )
  
  
  write_xlsx(
    list(
      Summary = summary_df
    ),
    summary_file
  )
  
  
  message(
    "\n>>> Bias summary saved: ",
    summary_file
  )
}
