# ==============================================================================
# SCRIPT: Homoeolog expression bias transitions and alluvial plots
#
# Description:
# This script visualizes transitions in homoeolog expression bias between
# Unprimed and Primed conditions.
#
# It uses the Bias_Analysis_<Lineage>.xlsx files generated by
# 05_homeolog_expression_bias.R and therefore does not recalculate expression
# bias, statistical tests, adjusted P values, or bias classifications.
#
# For each lineage, the script:
#   1. Reads the previously calculated bias classifications.
#   2. Counts transitions between Unprimed and Primed states.
#   3. Classifies transitions as Stable or Changed.
#   4. Generates an alluvial plot.
#   5. Exports transition counts and percentages.
#
# Expected bias categories:
#   - A bias
#   - C bias
#   - No bias
#
# Expected input columns:
#   gene_A, gene_C, Bias_UP, Bias_P, Flow, Transition_Type
# ==============================================================================


# ==============================================================================
# 1. Load required packages
# ==============================================================================

suppressPackageStartupMessages({
  library(readxl)
  library(dplyr)
  library(ggplot2)
  library(ggalluvial)
  library(writexl)
})


# ==============================================================================
# 2. Define input and output directories
# ==============================================================================

# BIAS_DIR:
# Directory containing Bias_Analysis_<Lineage>.xlsx files generated by
# 05_homeolog_expression_bias.R.
#
# OUTPUT_DIR:
# Directory where alluvial plots and transition summaries will be saved.

BIAS_DIR <- Sys.getenv(
  "BIAS_DIR",
  unset = "./results/Homeolog_expression_bias"
)

OUTPUT_DIR <- Sys.getenv(
  "OUTPUT_DIR",
  unset = "./results/Bias_transitions_alluvial"
)


if (!dir.exists(BIAS_DIR)) {
  stop(
    paste0(
      "Bias-analysis directory not found: ",
      BIAS_DIR,
      "\nRun 05_homeolog_expression_bias.R first or set BIAS_DIR correctly."
    )
  )
}


dir.create(
  OUTPUT_DIR,
  showWarnings = FALSE,
  recursive = TRUE
)


# ==============================================================================
# 3. Define analysis and plotting parameters
# ==============================================================================

# Replace these example lineage names with the names used in the output files
# generated by 05_homeolog_expression_bias.R.
lineages <- c("Line1", "Line2", "Line3")

label_UP <- "Unprimed"
label_P  <- "Primed"

# Order of bias categories in the alluvial plot.
bias_levels <- c(
  "A bias",
  "C bias",
  "No bias"
)

# Width and color of the bias-category boxes.
box_width <- 0.15
box_color_fill <- "#40E0D0"

# Colors used to distinguish stable and changed transitions.
flow_colors <- c(
  "Stable" = "#A6CEE3",
  "Changed" = "#E31A1C"
)


# ==============================================================================
# 4. Function: generate alluvial plot for one lineage
# ==============================================================================

generate_alluvial_plot <- function(
    df,
    lineage_name,
    out_path
) {
  
  # ---------------------------------------------------------------------------
  # 4.1. Validate required columns
  # ---------------------------------------------------------------------------
  
  required_columns <- c(
    "gene_A",
    "gene_C",
    "Bias_UP",
    "Bias_P",
    "Flow",
    "Transition_Type"
  )
  
  
  missing_columns <- setdiff(
    required_columns,
    colnames(df)
  )
  
  
  if (length(missing_columns) > 0) {
    stop(
      paste0(
        "Missing required columns for lineage '",
        lineage_name,
        "': ",
        paste(
          missing_columns,
          collapse = ", "
        )
      )
    )
  }
  
  
  # ---------------------------------------------------------------------------
  # 4.2. Retain valid bias classifications
  # ---------------------------------------------------------------------------
  
  df_clean <- df %>%
    filter(
      Bias_UP %in% bias_levels,
      Bias_P %in% bias_levels
    )
  
  
  if (nrow(df_clean) == 0) {
    warning(
      paste0(
        "No valid bias transitions were found for lineage '",
        lineage_name,
        "'."
      )
    )
    return(NULL)
  }
  
  
  # ---------------------------------------------------------------------------
  # 4.3. Summarize transitions
  # ---------------------------------------------------------------------------
  
  plot_data <- df_clean %>%
    count(
      Bias_UP,
      Bias_P,
      Flow,
      name = "Freq"
    ) %>%
    mutate(
      Bias_UP = factor(
        Bias_UP,
        levels = bias_levels
      ),
      Bias_P = factor(
        Bias_P,
        levels = bias_levels
      )
    )
  
  
  # ---------------------------------------------------------------------------
  # 4.4. Generate alluvial plot
  # ---------------------------------------------------------------------------
  
  p <- ggplot(
    plot_data,
    aes(
      y = Freq,
      axis1 = Bias_UP,
      axis2 = Bias_P
    )
  ) +
    geom_alluvium(
      aes(
        fill = Flow
      ),
      width = box_width,
      alpha = 0.8,
      curve_type = "cubic"
    ) +
    scale_fill_manual(
      values = flow_colors,
      name = "Transition"
    ) +
    geom_stratum(
      width = box_width,
      fill = box_color_fill,
      color = "black"
    ) +
    geom_text(
      stat = "stratum",
      aes(
        label = paste0(
          after_stat(stratum),
          "\n(n=",
          after_stat(count),
          ")"
        )
      ),
      size = 3
    ) +
    scale_x_discrete(
      limits = c(
        label_UP,
        label_P
      ),
      expand = c(
        0.1,
        0.1
      ),
      position = "top"
    ) +
    labs(
      title = paste0(
        lineage_name,
        ": Homoeolog Expression Bias Transitions"
      ),
      y = "Gene Pairs",
      x = NULL
    ) +
    theme_minimal() +
    theme(
      panel.grid = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks = element_blank(),
      axis.title.y = element_text(
        margin = margin(
          t = 0,
          r = -15,
          b = 0,
          l = 0
        )
      ),
      axis.text.x = element_text(
        size = 12,
        face = "bold",
        margin = margin(
          b = -10
        )
      ),
      plot.title = element_text(
        hjust = 0.5,
        face = "bold"
      ),
      legend.position = "right",
      legend.box.spacing = unit(
        0.2,
        "cm"
      ),
      legend.margin = margin(
        l = 0
      )
    )
  
  
  output_file <- file.path(
    out_path,
    paste0(
      "Bias_Transitions_Alluvial_",
      lineage_name,
      ".png"
    )
  )
  
  
  ggsave(
    output_file,
    p,
    width = 7,
    height = 6,
    bg = "white",
    dpi = 300
  )
  
  
  message(
    "  -> Alluvial plot saved: ",
    output_file
  )
  
  
  # ---------------------------------------------------------------------------
  # 4.5. Generate transition summary
  # ---------------------------------------------------------------------------
  
  total_pairs <- nrow(
    df_clean
  )
  
  
  transition_summary <- df_clean %>%
    count(
      Bias_UP,
      Bias_P,
      Flow,
      Transition_Type,
      name = "n"
    ) %>%
    mutate(
      Lineage = lineage_name,
      Total = total_pairs,
      Percent = round(
        (n / total_pairs) * 100,
        2
      )
    ) %>%
    select(
      Lineage,
      Bias_UP,
      Bias_P,
      Flow,
      Transition_Type,
      n,
      Total,
      Percent
    )
  
  
  flow_summary <- df_clean %>%
    count(
      Flow,
      name = "n"
    ) %>%
    mutate(
      Lineage = lineage_name,
      Total = total_pairs,
      Percent = round(
        (n / total_pairs) * 100,
        2
      )
    ) %>%
    select(
      Lineage,
      Flow,
      n,
      Total,
      Percent
    )
  
  
  return(
    list(
      transition_summary = transition_summary,
      flow_summary = flow_summary
    )
  )
}


# ==============================================================================
# 5. Generate alluvial plots and summaries for all lineages
# ==============================================================================

message(
  ">>> Generating homoeolog expression bias transition plots..."
)


transition_summaries <- list()
flow_summaries <- list()


for (lin in lineages) {
  
  message(
    paste0(
      "\n--------------------------------------------------"
    )
  )
  
  message(
    paste0(
      "Processing lineage: ",
      lin
    )
  )
  
  
  bias_file <- file.path(
    BIAS_DIR,
    paste0(
      "Bias_Analysis_",
      lin,
      ".xlsx"
    )
  )
  
  
  if (!file.exists(bias_file)) {
    warning(
      paste0(
        "Bias-analysis file not found for lineage '",
        lin,
        "': ",
        bias_file
      )
    )
    next
  }
  
  
  df_bias <- read_excel(
    bias_file
  )
  
  
  result <- generate_alluvial_plot(
    df_bias,
    lin,
    OUTPUT_DIR
  )
  
  
  if (!is.null(result)) {
    transition_summaries[[lin]] <- result$transition_summary
    flow_summaries[[lin]] <- result$flow_summary
  }
}


# ==============================================================================
# 6. Export combined transition summaries
# ==============================================================================

if (length(transition_summaries) > 0) {
  
  transition_summary_all <- bind_rows(
    transition_summaries
  )
  
  flow_summary_all <- bind_rows(
    flow_summaries
  )
  
  
  summary_file <- file.path(
    OUTPUT_DIR,
    "Bias_Transition_Summary_All_Lineages.xlsx"
  )
  
  
  write_xlsx(
    list(
      Transition_Summary = transition_summary_all,
      Stable_vs_Changed = flow_summary_all
    ),
    summary_file
  )
  
  
  message(
    "\n>>> Transition summary saved: ",
    summary_file
  )
}
