# ==============================================================================
# SCRIPT: Identification and visualization of core homoeolog bias-transition pairs
#
# Description:
# This script identifies homoeologous gene pairs that change their expression
# bias state upon priming across all analyzed lineages.
#
# The workflow:
#   1. Reads Bias_Analysis_<Lineage>.xlsx files generated by script 05.
#   2. Extracts homoeologous gene pairs classified as "Changed".
#   3. Generates a Venn diagram comparing changed pairs across lineages.
#   4. Identifies the core intersection of pairs changing in all lineages.
#   5. Extracts Log2FC values to build a comparative heatmap of core pairs.
#   6. Calculates transition magnitude (Delta) and direction consistency.
#   7. Exports changed-pair lists, the core intersection, summary counts, and
#      the final candidate table.
#
# IMPORTANT:
# This script does not recalculate homoeolog expression bias, statistical tests,
# adjusted P values, or bias classifications. It uses the results generated by
# 05_homeolog_expression_bias.R.
#
# NOTE:
# This script is currently optimized for exactly 3 lineages/genotypes for Venn
# visualization and downstream core-intersection analysis.
#
# Optional annotation file:
# If ANNOTATION_FILE is provided, it must contain the following columns:
#   - DarmorV10
#   - All_Uniprot_Prot
# ==============================================================================


# ==============================================================================
# 1. Load required packages
# ==============================================================================

suppressPackageStartupMessages({
  library(tidyverse)
  library(readxl)
  library(writexl)
  library(ggVennDiagram)
  library(pheatmap)
})


# ==============================================================================
# 2. Define input and output paths
# ==============================================================================

# BIAS_DIR:
# Directory containing Bias_Analysis_<Lineage>.xlsx files generated by
# 05_homeolog_expression_bias.R.
#
# ANNOTATION_FILE:
# Optional annotation table used to add gene names to the heatmap and final
# candidate table.
#
# OUTPUT_DIR:
# Directory where Venn diagrams, heatmaps, pair lists, and candidate tables
# will be saved.

BIAS_DIR <- Sys.getenv(
  "BIAS_DIR",
  unset = "./results/Homeolog_expression_bias"
)

ANNOTATION_FILE <- Sys.getenv(
  "ANNOTATION_FILE",
  unset = "./reference/DarmorV10_Final_Annotation.xlsx"
)

OUTPUT_DIR <- Sys.getenv(
  "OUTPUT_DIR",
  unset = "./results/Core_bias_transitions"
)


# Replace these example lineage names with the names used in the output files
# generated by 05_homeolog_expression_bias.R.
lineages <- c(
  "Line1",
  "Line2",
  "Line3"
)


# This script is currently designed for exactly three lineages.
if (length(lineages) != 3) {
  stop(
    "This script is currently designed for exactly 3 lineages/genotypes."
  )
}


if (!dir.exists(BIAS_DIR)) {
  stop(
    paste0(
      "Bias-analysis directory not found: ",
      BIAS_DIR,
      "\nRun 05_homeolog_expression_bias.R first or set BIAS_DIR correctly."
    )
  )
}


dir.create(
  OUTPUT_DIR,
  showWarnings = FALSE,
  recursive = TRUE
)


# ==============================================================================
# 3. Extract homoeologous pairs with bias transitions for each lineage
# ==============================================================================

message(
  ">>> Extracting homoeologous pairs with bias transitions..."
)


changed_pair_lists <- list()


for (lin in lineages) {
  
  bias_file <- file.path(
    BIAS_DIR,
    paste0(
      "Bias_Analysis_",
      lin,
      ".xlsx"
    )
  )
  
  
  if (!file.exists(bias_file)) {
    stop(
      paste0(
        "Bias-analysis file not found for lineage '",
        lin,
        "': ",
        bias_file
      )
    )
  }
  
  
  df <- read_excel(
    bias_file
  )
  
  
  required_columns <- c(
    "gene_A",
    "gene_C",
    "Flow"
  )
  
  
  missing_columns <- setdiff(
    required_columns,
    colnames(df)
  )
  
  
  if (length(missing_columns) > 0) {
    stop(
      paste0(
        "Missing required columns in ",
        bias_file,
        ": ",
        paste(
          missing_columns,
          collapse = ", "
        )
      )
    )
  }
  
  
  changed_pairs <- df %>%
    filter(
      Flow == "Changed"
    ) %>%
    select(
      gene_A,
      gene_C
    ) %>%
    distinct()
  
  
  changed_pair_lists[[lin]] <- changed_pairs
  
  
  message(
    sprintf(
      "  Lineage %s: %d homoeologous pairs changed bias state.",
      lin,
      nrow(changed_pairs)
    )
  )
}


if (length(changed_pair_lists) != 3) {
  stop(
    "Changed-pair data were not successfully collected for all 3 lineages."
  )
}


# ==============================================================================
# 4. Generate Venn diagram of changed homoeologous pairs
# ==============================================================================

message(
  ">>> Generating Venn diagram of changed homoeologous pairs..."
)


# ggVennDiagram expects vectors. Each A-C pair is therefore represented by a
# single temporary identifier combining gene_A and gene_C.
venn_lists <- lapply(
  changed_pair_lists,
  function(df) {
    paste(
      df$gene_A,
      df$gene_C,
      sep = "__"
    )
  }
)


p_venn <- ggVennDiagram(
  venn_lists,
  label_alpha = 0,
  set_color = c(
    "#104E8B",
    "#fee08b",
    "#CD0000"
  ),
  edge_size = 0.5
) +
  scale_fill_gradient(
    low = "#F7FBFF",
    high = "#08306B"
  ) +
  ggtitle(
    "Shared homoeologous pairs with bias changes across lineages"
  ) +
  theme(
    plot.title = element_text(
      hjust = 0.5,
      face = "bold"
    )
  )


venn_file <- file.path(
  OUTPUT_DIR,
  "Venn_Changed_Homoeologous_Pairs.png"
)


ggsave(
  venn_file,
  p_venn,
  width = 6,
  height = 6,
  bg = "white"
)


message(
  "  -> Venn diagram saved: ",
  venn_file
)


# ==============================================================================
# 5. Identify the core intersection
# ==============================================================================

# The unit of intersection is the complete homoeologous pair:
# gene_A + gene_C.

intersect_pairs <- function(df1, df2) {
  
  inner_join(
    df1,
    df2,
    by = c(
      "gene_A",
      "gene_C"
    )
  ) %>%
    distinct(
      gene_A,
      gene_C
    )
}


common_all <- Reduce(
  intersect_pairs,
  changed_pair_lists
)


n_core <- nrow(
  common_all
)


message(
  sprintf(
    "\n>>> Found %d core homoeologous pairs that changed bias state in all lineages.",
    n_core
  )
)


# ==============================================================================
# 6. Export changed-pair lists and core intersection
# ==============================================================================

summary_counts <- tibble(
  Category = c(
    paste0(
      "Changed_",
      lineages
    ),
    "Core_all_lineages"
  ),
  Count = c(
    vapply(
      changed_pair_lists,
      nrow,
      integer(1)
    ),
    n_core
  )
)


pair_list_file <- file.path(
  OUTPUT_DIR,
  "Changed_Pairs_and_Core_Intersection.xlsx"
)


pair_sheets <- c(
  changed_pair_lists,
  list(
    Core_Intersection = common_all,
    Summary_Counts = summary_counts
  )
)


write_xlsx(
  pair_sheets,
  pair_list_file
)


message(
  "  -> Changed-pair lists and core intersection saved: ",
  pair_list_file
)


# ==============================================================================
# 7. Continue only if a core intersection exists
# ==============================================================================

if (n_core > 0) {
  
  
  # ============================================================================
  # 7.1. Load optional annotation
  # ============================================================================
  
  annotation_df <- NULL
  
  
  if (file.exists(ANNOTATION_FILE)) {
    
    message(
      ">>> Loading annotation file..."
    )
    
    
    annotation_raw <- read_excel(
      ANNOTATION_FILE
    )
    
    
    required_annotation_columns <- c(
      "DarmorV10",
      "All_Uniprot_Prot"
    )
    
    
    missing_annotation_columns <- setdiff(
      required_annotation_columns,
      colnames(annotation_raw)
    )
    
    
    if (length(missing_annotation_columns) > 0) {
      stop(
        paste0(
          "The annotation file is missing required columns: ",
          paste(
            missing_annotation_columns,
            collapse = ", "
          ),
          "\nRequired columns are: DarmorV10 and All_Uniprot_Prot."
        )
      )
    }
    
    
    annotation_df <- annotation_raw %>%
      select(
        DarmorV10,
        All_Uniprot_Prot
      ) %>%
      distinct()
    
    
  } else {
    
    message(
      "  [INFO] Annotation file not found. Proceeding without gene names."
    )
  }
  
  
  # ============================================================================
  # 7.2. Extract Log2FC and bias information for core pairs
  # ============================================================================
  
  get_candidate_data <- function(lin) {
    
    file_path <- file.path(
      BIAS_DIR,
      paste0(
        "Bias_Analysis_",
        lin,
        ".xlsx"
      )
    )
    
    
    df <- read_excel(
      file_path
    )
    
    
    required_columns <- c(
      "gene_A",
      "gene_C",
      "LFC_UP",
      "LFC_P",
      "Bias_UP",
      "Bias_P"
    )
    
    
    missing_columns <- setdiff(
      required_columns,
      colnames(df)
    )
    
    
    if (length(missing_columns) > 0) {
      stop(
        paste0(
          "Missing required columns in ",
          file_path,
          ": ",
          paste(
            missing_columns,
            collapse = ", "
          )
        )
      )
    }
    
    
    df %>%
      semi_join(
        common_all,
        by = c(
          "gene_A",
          "gene_C"
        )
      ) %>%
      select(
        gene_A,
        gene_C,
        LFC_UP,
        LFC_P,
        Bias_UP,
        Bias_P
      ) %>%
      mutate(
        !!paste0(
          "LFC_",
          lin,
          "_UP"
        ) := LFC_UP,
        
        !!paste0(
          "LFC_",
          lin,
          "_P"
        ) := LFC_P,
        
        !!paste0(
          "Bias_",
          lin
        ) := paste0(
          Bias_UP,
          " -> ",
          Bias_P
        )
      ) %>%
      select(
        -LFC_UP,
        -LFC_P,
        -Bias_UP,
        -Bias_P
      )
  }
  
  
  candidate_data_list <- lapply(
    lineages,
    get_candidate_data
  )
  
  
  candidates_df <- Reduce(
    function(x, y) {
      left_join(
        x,
        y,
        by = c(
          "gene_A",
          "gene_C"
        )
      )
    },
    candidate_data_list
  )
  
  
  # ============================================================================
  # 7.3. Add optional gene annotation
  # ============================================================================
  
  if (!is.null(annotation_df)) {
    
    candidates_df <- candidates_df %>%
      left_join(
        annotation_df,
        by = c(
          "gene_A" = "DarmorV10"
        )
      ) %>%
      rename(
        Gene_name = All_Uniprot_Prot
      )
    
    
  } else {
    
    candidates_df <- candidates_df %>%
      mutate(
        Gene_name = NA_character_
      )
  }
  
  
  # ============================================================================
  # 8. Generate heatmap of core homoeologous pairs
  # ============================================================================
  
  message(
    ">>> Generating heatmap for core homoeologous pairs..."
  )
  
  
  heatmap_df <- candidates_df %>%
    mutate(
      Gene_Label = ifelse(
        is.na(Gene_name) |
          Gene_name == "",
        gene_A,
        paste0(
          gene_A,
          " (",
          Gene_name,
          ")"
        )
      )
    )
  
  
  lfc_cols <- grep(
    "^LFC_",
    colnames(heatmap_df),
    value = TRUE
  )
  
  
  heatmap_matrix <- heatmap_df %>%
    select(
      Gene_Label,
      all_of(
        lfc_cols
      )
    ) %>%
    column_to_rownames(
      "Gene_Label"
    ) %>%
    as.matrix()
  
  
  # Use a symmetric color scale centered at zero.
  max_val <- max(
    abs(
      heatmap_matrix
    ),
    na.rm = TRUE
  )
  
  
  # Avoid a degenerate color scale if all values are zero.
  if (!is.finite(max_val) || max_val == 0) {
    max_val <- 1
  }
  
  
  my_breaks <- seq(
    -max_val,
    max_val,
    length.out = 101
  )
  
  
  my_color <- colorRampPalette(
    c(
      "#2166AC",
      "white",
      "#B2182B"
    )
  )(100)
  
  
  heatmap_file <- file.path(
    OUTPUT_DIR,
    "Heatmap_Core_Bias_Transition_Pairs.png"
  )
  
  
  png(
    heatmap_file,
    width = 1200,
    height = 1600,
    res = 150
  )
  
  
  pheatmap(
    heatmap_matrix,
    color = my_color,
    breaks = my_breaks,
    cluster_rows = TRUE,
    cluster_cols = FALSE,
    show_rownames = TRUE,
    show_colnames = TRUE,
    angle_col = 45,
    treeheight_row = 15,
    treeheight_col = 0,
    main = paste0(
      "Core homoeologous pairs with bias transitions (log2 A/C) - n=",
      n_core
    ),
    fontsize = 10
  )
  
  
  dev.off()
  
  
  message(
    "  -> Heatmap saved: ",
    heatmap_file
  )
  
  
  # ============================================================================
  # 9. Calculate transition magnitude and direction consistency
  # ============================================================================
  
  message(
    ">>> Calculating transition magnitude and direction consistency..."
  )
  
  
  # Create lineage-specific Delta and Direction columns.
  for (lin in lineages) {
    
    lfc_up_col <- paste0(
      "LFC_",
      lin,
      "_UP"
    )
    
    lfc_p_col <- paste0(
      "LFC_",
      lin,
      "_P"
    )
    
    delta_col <- paste0(
      "Delta_",
      lin
    )
    
    direction_col <- paste0(
      "Direction_",
      lin
    )
    
    
    candidates_df[[delta_col]] <- abs(
      candidates_df[[lfc_p_col]] -
        candidates_df[[lfc_up_col]]
    )
    
    
    candidates_df[[direction_col]] <- sign(
      candidates_df[[lfc_p_col]] -
        candidates_df[[lfc_up_col]]
    )
  }
  
  
  delta_cols <- paste0(
    "Delta_",
    lineages
  )
  
  
  direction_cols <- paste0(
    "Direction_",
    lineages
  )
  
  
  candidates_df$Mean_Delta <- rowMeans(
    candidates_df[
      delta_cols
    ],
    na.rm = TRUE
  )
  
  
  candidates_df$Consistency <- apply(
    candidates_df[
      direction_cols
    ],
    1,
    function(x) {
      
      x <- x[
        !is.na(x)
      ]
      
      
      if (length(x) != length(lineages)) {
        return(
          "Incomplete"
        )
      }
      
      
      if (length(unique(x)) == 1) {
        return(
          "Consistent"
        )
      }
      
      
      return(
        "Divergent"
      )
    }
  )
  
  
  # ============================================================================
  # 10. Format and export final candidate table
  # ============================================================================
  
  message(
    ">>> Formatting core-pair candidate table..."
  )
  
  
  final_table <- candidates_df %>%
    select(
      GeneID_BnA = gene_A,
      GeneID_BnC = gene_C,
      Gene_name,
      all_of(
        paste0(
          "Bias_",
          lineages
        )
      ),
      all_of(
        unlist(
          lapply(
            lineages,
            function(lin) {
              c(
                paste0(
                  "LFC_",
                  lin,
                  "_UP"
                ),
                paste0(
                  "LFC_",
                  lin,
                  "_P"
                )
              )
            }
          )
        )
      ),
      all_of(
        delta_cols
      ),
      Mean_Delta,
      Consistency
    ) %>%
    arrange(
      desc(
        Mean_Delta
      )
    )
  
  
  table_file <- file.path(
    OUTPUT_DIR,
    "Candidate_Core_Homoeologous_Pairs.xlsx"
  )
  
  
  write_xlsx(
    list(
      Core_Homoeologous_Pairs = final_table
    ),
    table_file
  )
  
  
  message(
    "  -> Core-pair candidate table saved: ",
    table_file
  )
  
  
} else {
  
  message(
    "  [INFO] No core homoeologous pairs were found. Heatmap and candidate table were skipped."
  )
}